# Revision

In [1]:
# import the iris dataset
from IPython.display import IFrame

In [2]:
IFrame('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', width=300, height=200)

In [3]:
# import the load_iris function from the dataset module
from sklearn.datasets import load_iris

In [4]:
# create an object/variable that will hold the iris dataset
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [5]:
# print the iris data
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
# print the names of the four features
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
# print integers representing the species of each observation
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
# print the encoding scheme for species: 0 = setosa, 1 = versicolor, 2 = virginica
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [11]:
# check the type and shape of features and responses
print(type(iris.data))
print(iris.data.shape)
print(type(iris.target))
print(iris.target.shape)

<class 'numpy.ndarray'>
(150, 4)
<class 'numpy.ndarray'>
(150,)


In [12]:
# store the feature matrix in 'X' and response vector in 'y'
X = iris.data
y = iris.target

In [13]:
# print the shape of X and y
print(X.shape)
print(y.shape)

(150, 4)
(150,)


<b>Implementing KNN on iris dataset</b>

In [14]:
# Step1: Import the class you plan to you
from sklearn.neighbors import KNeighborsClassifier

In [16]:
# Step2: Instantiate the class object
knn = KNeighborsClassifier(n_neighbors=1)
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [17]:
# Step3: Fit the model with the data
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [18]:
# Step4: Make predictions for an out-of-sample observation
knn.predict([[3, 5, 4, 2]])

array([2])

In [19]:
# Another sample set with multiple tuples processed for prediction
X_new = [[3, 5,  4, 2], [5, 4, 3, 2]]
knn.predict(X_new)

array([2, 1])

<b>Implementing KNN via a different value of K (K=5)</b>

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [21]:
knn.predict(X_new)

array([1, 1])

<b>Using a different classification model</b> "Logistic Regression"

In [22]:
# Step1: Import the required class
from sklearn.linear_model import LogisticRegression

# Step2: Instantiate the class object
logreg = LogisticRegression()

# Step3: Fit the model to the data
logreg.fit(X, y)

# Step4: Make predictions for an out-of-sample observation
logreg.predict(X_new)

array([2, 0])

<b>Comparing Machine Learning models within scikit-learn</b>

- Evaluation Procedure #1: Train and Test the model on the entire dataset (Training Accuracy)

In [23]:
# read the iris dataset
from sklearn.datasets import load_iris
iris = load_iris()

# create X and y (features and responses)
X = iris.data
y = iris.target

<b>1. Logistic Regression</b>

In [25]:
# Step1: import the class
from sklearn.linear_model import LogisticRegression

# Step2: instantiate the model using the default parameters
logreg = LogisticRegression()

# Step3: fit the model with the data
logreg.fit(X, y)

# Step4: predict the response values for the observations
logreg.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
# Step5: store the predicted response values in a variable y_pred
y_pred = logreg.predict(X)

In [28]:
# Step 6: compute the classification accuracy for the model using the accuracy_score function
from sklearn import metrics
print(metrics.accuracy_score(y, y_pred))

0.96


<b>1. KNN(5)</b>

In [29]:
# Step1: import the relevant class
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# Step2: instantiate the object
knn = KNeighborsClassifier(n_neighbors=5)

# Step3: fit the model
knn.fit(X, y)

# Step4: store the predictions in y_pred
y_pred = knn.predict(X)

# Step5: calculate the training accuracy
print(metrics.accuracy_score(y, y_pred))

0.9666666666666667


<b>1. KNN(1)</b>

In [30]:
# Step1: import the relevant class
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# Step2: instantiate the object
knn = KNeighborsClassifier(n_neighbors=1)

# Step3: fit the model
knn.fit(X, y)

# Step4: store the predictions in y_pred
y_pred = knn.predict(X)

# Step5: calculate the training accuracy
print(metrics.accuracy_score(y, y_pred))

1.0


- Evaluation Procedure #2: Train-Test Split

In [31]:
# print the shape of X and y
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [32]:
# Step1: Split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [33]:
# print the shapes of the new objects
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(90, 4)
(60, 4)
(90,)
(60,)


<b>1. Logistic Regression</b>

In [34]:
# Step2: train the model on the training set
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
# Step3: make predictions on the testing set and store them in y_pred
y_pred = logreg.predict(X_test)

# Step4: compare actual response values with (y_test) with the predicted values (y_pred)
print(metrics.accuracy_score(y_test, y_pred))

0.95


<b>2. KNN(5)</b>

In [36]:
# Step2: train the model on the training set
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# Step3: make predictions on the testing set and store them in y_pred
y_pred = knn.predict(X_test)

# Step4: compare actual response values with (y_test) with the predicted values (y_pred)
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667


<b>3. KNN(1)</b>

In [37]:
# Step2: train the model on the training set
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

# Step3: make predictions on the testing set and store them in y_pred
y_pred = knn.predict(X_test)

# Step4: compare actual response values with (y_test) with the predicted values (y_pred)
print(metrics.accuracy_score(y_test, y_pred))

0.95


<b>Finding the best value for K</b>